# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 18:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('awesome_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('gameuser_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='awesome_users.GameUser')),
            ],
            options={
                'abstract': False,
            },
            bases=('awesome_users.gameuser',),
        ),
    ]
