# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 12:41
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'tokens', app_label='game')


def unload_fixture(apps, schema_editor):
    MyModel = apps.get_model("authtoken", "Token")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
